language: node_js

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

before_install:
  # Install headless browser
  - java -version
  - wget http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar -O selenium.jar
  - java -jar selenium.jar &
  - npm install -g phantomjs-prebuilt
  - phantomjs -v
  # Install testing library
  - npm install -g nightwatch
  - nightwatch -v
  # Install Rust
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustc --version
  - cargo --version
  # Build and run Polaris server
  - git clone http://github.com/agersant/polaris
  - cd polaris
  - cargo build
  - cargo run -- -d test/db.sqlite -w .. &
  - cd ..

script:
  - sleep 2
  - nightwatch